// Generated by CoffeeScript 1.6.3
(function() {
  var ng;

  ng = angular.module('myApp', ['ui.router']);

  ng.run(function(jeebus) {
    return jeebus.connect('blinker');
  });

  ng.controller('MainCtrl', function($scope, jeebus) {
    $scope.button = function(button, value) {
      jeebus.send({
        button: button,
        value: value
      });
      return jeebus.rpc('db-get', '/admin/started').then(function(r) {
        return console.log('rpc', r);
      });
    };
    $scope.echoTest = function() {
      jeebus.send("echoTest!");
      return jeebus.rpc('echo', 'Echo', 'me!').then(function(r) {
        return $scope.message = r;
      });
    };
    $scope.dbGetTest = function() {
      return jeebus.rpc('db-get', '/admin/started').then(function(r) {
        return $scope.message = r;
      });
    };
    return $scope.dbKeysTest = function() {
      return jeebus.rpc('db-keys', '/').then(function(r) {
        return $scope.message = r;
      });
    };
  });

}).call(this);
