// Generated by CoffeeScript 1.7.1
(function() {
  var ng,
    __slice = [].slice;

  ng = angular.module('myApp');

  ng.value('appInfo', {
    name: 'HouseMon',
    version: '0.9.0',
    home: 'https://github.com/jcw/housemon'
  });

  ng.provider('navbar', function() {
    var navs;
    navs = [];
    return {
      add: function(route, title, weight) {
        if (weight == null) {
          weight = 50;
        }
        return navs.push({
          route: route,
          title: title,
          weight: weight
        });
      },
      del: function(route) {
        return navs = navs.filter(function(x) {
          return x.route !== route;
        });
      },
      $get: function() {
        return navs.sort(function(a, b) {
          return a.weight - b.weight;
        });
      }
    };
  });

  ng.config(function($urlRouterProvider, $locationProvider) {
    $urlRouterProvider.otherwise('/');
    return $locationProvider.html5Mode(true);
  });

  ng.run(function($rootScope, appInfo) {
    $rootScope.appInfo = appInfo;
    return $rootScope.shared = {};
  });

  ng.controller('NavCtrl', function($scope, navbar) {
    return $scope.navbar = navbar;
  });

  ng.directive('appVersion', function(appInfo) {
    return function(scope, elm, attrs) {
      return elm.text(appInfo.version);
    };
  });

  ng.config(function($stateProvider, navbarProvider) {
    $stateProvider.state('jeebus', {
      url: '/jeebus',
      templateUrl: 'jeebus/view.html',
      controller: 'JeeBusCtrl'
    });
    return navbarProvider.add('/jeebus', 'JeeBus', 25);
  });

  ng.controller('JeeBusCtrl', function($scope, jeebus) {
    $scope.echoTest = function() {
      jeebus.send("echoTest!");
      return jeebus.rpc('echo', 'Echo', 'me!').then(function(r) {
        return $scope.message = r;
      });
    };
    $scope.dbGetTest = function() {
      return jeebus.rpc('db-get', '/jeebus/started').then(function(r) {
        return $scope.message = r;
      });
    };
    return $scope.dbKeysTest = function() {
      return jeebus.rpc('db-keys', '/').then(function(r) {
        return $scope.message = r;
      });
    };
  });

  ng.run(function(jeebus) {
    return jeebus.connect('housemon', 3335);
  });

  ng.factory('HM', function(jeebus) {
    var keyAsPath;
    keyAsPath = function(key) {
      if (key.length === 0) {
        return '/';
      }
      return "/" + (key.join('/')) + "/";
    };
    return {
      keys: function() {
        var key;
        key = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return jeebus.rpc('db-keys', keyAsPath(key));
      },
      get: function() {
        var key;
        key = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return jeebus.rpc('db-get', keyAsPath(key));
      },
      set: function() {
        var key, value, _i;
        key = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), value = arguments[_i++];
        jeebus.store(keyAsPath(key), value);
        return this;
      },
      attach: function() {
        var key;
        key = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return jeebus.attach(keyAsPath(key));
      },
      detach: function() {
        var key;
        key = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        jeebus.detach(keyAsPath(key));
        return this;
      }
    };
  });

}).call(this);
